name:                codex
version:             1.0.0
github:              "pbv/codex"
license:             MIT
author:              "Pedro Baltazar Vasconcelos"
maintainer:          "pbv@dcc.fc.up.pt"
copyright:           "2021 Pedro Baltazar Vasconcelos"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/pbv/codex/README.md>

dependencies:
- Glob
- aeson
- async
- base >= 4.7 && < 5
- blaze-builder
- bytestring
- configurator
- containers
- directory
- filepath
- hashable
- heist
- io-streams
- ldap-client
- lens
- lifted-base                
- map-syntax
- monad-control
- mtl
- network-uri
- pandoc
- pandoc-types
- process
- shellwords
- random
- snap
- snap-core
- snap-loader-static
- snap-server
- snap-web-routes
- snaplet-sqlite-simple
- sqlite-simple
- temporary
- text
- time
- transformers
- unix
- unordered-containers
- utf8-string
- web-routes
- xmlhtml
- http-types
- regex-compat
- myers-diff

executables:
  codex-server:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -W


