packages:
- .

allow-newer: true

extra-deps:
  - ldap-client-0.4.2
  - snap-server-1.1.2.1
  - snap-1.1.3.3
  - snap-loader-static-1.0.0.1
  - snap-web-routes-0.5.1.0
  - snaplet-sqlite-simple-1.0.0.2
  - fast-myers-diff-0.0.1

resolver: lts-21.9

ghc-options:
    "$everything": -split-sections