packages:
- .

allow-newer: true

extra-deps:
- heist-1.1
- ldap-client-0.2.0
- map-syntax-0.3
- snap-1.1.1.0
- snap-loader-static-1.0.0.0
- snap-web-routes-0.5.1.0
- snaplet-sqlite-simple-1.0.0.2
- xmlhtml-0.2.5.2
- pwstore-fast-2.4.4
- shellwords-0.1.2.1

resolver: lts-12.13

  