packages:
- '.'
- '../snaplet-sqlite-simple'

allow-newer: true

extra-deps:
   - ldap-client-0.4.3
   - snap-loader-static-1.0.0.1
   - snap-web-routes-0.5.1.0

resolver: lts-24.50

ghc-options:
    "$everything": -split-sections
    